### ISSUE TITLE
mAtra error

### ISSUE THREAD

**Issue by vvasuki** [KYVeda/texts#1]
You use the devanAgarI maatraa कॆ instead of के and कॊ instead of को। This violates the common devanAgari orthographic convention of representing hrasva-svara-s with the curved marks. 

For example, https://github.com/KYVeda/texts/blob/master/TS-Padam/TS-2.1/TS%202.1%20Sanskrit%20Padam.BRH correctly uses "E"  for "ए"। However, the [generated pdf](https://github.com/KYVeda/texts/blob/master/TS-Padam/TS-2.1/TS%202.1%20Sanskrit%20Pada%20Paatam%20with%20Vaakyam.pdf) uses the wrong mAtrA. Why?

**Comment by vedavms** [comment]
Dear VishvAs,
I am attaching two pdfs herewith explaining the basic problem that was
observed by a member using Sanskrit and also later pointed out by Sanskrit
Documents.com and you.
We need to use 'e' and 'o' with small letters for the mAtrA to be reflected
correctly. (review document where 'e' and 'o' have been used.
This seems to be little odd from Baraha. There is no hrava letter in
Sanskrit traditional text.
They could have mapped 'E; and 'O;.
Conversion with 'e' and 'o' small letters gives hrasva 'ae' and 'o' which
are available in Tamil, Malayalam and other languages.

Solution: We have nearly 2000 A4 pages equivalent of word document in
Sanskrit. The mAtrA of 'E' and 'O; can be cut and pasted or replaced with
'e' or 'o' mAtrAs which are better represented.. ie it is separate
component of a basic letter (akshara) . We need to find and replace in all
the documents. Can you please make us a small program or routine that runs
in word and a similar one for Baraha document which is nothing but an
English document with codes.

thanks and best regards
VedaVMS Admin

**Comment by vvasuki** [comment]
Mechanically replacing in multiple word documents is difficult. It is much better to replace E and O in baraha files with e and o respectively. One can then convert the devanAgarI text to dravidian languages (rather than getting them from baraha files)? what do you think?

**Comment by vedavms** [comment]
Dear VishvAs,
I noted your view point. It is easy to replace the Baraha files. The
difficulty is in Word files, as we format in a detailed way to see that
mantras do not get broken between pages (except for large mantras) and in
case of continuous text like samhitA atleast logical parts are together. I
thought there will be way in word.
Let me think over.
*Second issue of converting directly to vernacular language*.
We have no experience with *direct translation.* But if you can demonstrate
a few page or one Suktham like GanapatyatharvaSeerSham for this concept, we
will be more than happy. I think you will be using unicode.
We as a team can vouch for Tamil and Malayalam languages if you convert any
sample from our existing document. We have no knowledge of language/akshara
specific issues in other languages.
One good news if that a group based on Canada are sending first Telugu and
Kannada copy of Shanti Japa book next week. We can take feedback from them.
They use Baraha for publishing slokas, mantras in Telugu, Kannada and even
in English (some overseas students use English texts for learning slokas,
mantras etc.)
Please think over the issue of representing Vedic symbols as per Sanskrit
aksharas in other languages example nasal symbol, avagraha symbol etc. gm
and gg can be represented in vernacular languages in brackets ( we did that
initially) when you directly transliterate!!
regards
Sethuraman

**Comment by vedavms** [comment]
Now the mAtrAs have been repalced in all files. We have taken steps to code Sanskrit Baraha files with small 'e' and 'o' hence we can close this issue
thanks
